### ISSUE TITLE
로그인, 로그아웃 구현

### ISSUE THREAD

**Issue by dahyen0o** [DEMODAY-devStory/backend#6]

**Comment by dahyen0o** [comment]
@taeho0888 확인 부탁드립니당

### 회원가입 수정

- 회원가입 시  데이터베이스에 회원 정보 바로 저장 -> ```UserManager.create_user()``` 거쳐 회원가입 되게 함

  - 일반 유저로 회원가입을 할 경우 비밀번호가 암호화되지 않았는데 이제는 암호화 됨
  - 일반 유저와 어드민 유저가 똑같은 로직을 거쳐 회원가입이 됨

- date_joined, before_last_login 컬럼 추가

  - date_joined: 회원가입한 시각
  - before_last_login: 마지막으로 로그인한 시간 (주의: last_login은 현재 로그인한 시간)

- 코드 깔끔하게 수정

<br>

### 로그인, 로그아웃 구현

- 백에서 로그인, 로그아웃 되게 함

  - 세션에 저장 됨

- Response 내용 깔끔하게 수정

**Comment by taeho0888** [comment]
최고다..
