### ISSUE TITLE
프로필 쪽 모델, 디비 정하기

### ISSUE THREAD

**Issue by dahyen0o** [DEMODAY-devStory/backend#8]
with @taeho0888

**Comment by taeho0888** [comment]
![dbdb](https://user-images.githubusercontent.com/105200642/194068549-aad99117-ee96-4926-bf66-c6958a87d981.png)

**Comment by dahyen0o** [comment]
project.name -> project.project_name (skill.skill_name과 통일성 위해)
career.program -> career.skill (기술 스택)

**Comment by dahyen0o** [comment]
hashtag 테이블의 pk = hashtag_name
hashtag 테이블과 profile 테이블은 manyToMany 관계

**Comment by taeho0888** [comment]
![image](https://user-images.githubusercontent.com/105200642/194117281-9ea1a84b-b891-472d-aced-47d5dd5a7aab.png)
